//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indico.Custom.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Indico.Custom.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds labled data to a custom collection.
        /// </summary>
        internal static string AddDataDescription {
            get {
                return ResourceManager.GetString("AddDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Data.
        /// </summary>
        internal static string AddDataDisplayName {
            get {
                return ResourceManager.GetString("AddDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of indico Custom Collections.
        /// </summary>
        internal static string CollectionListResultsDescription {
            get {
                return ResourceManager.GetString("CollectionListResultsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string CollectionListResultsDisplayName {
            get {
                return ResourceManager.GetString("CollectionListResultsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico Custom Scope.
        /// </summary>
        internal static string IndicoScope {
            get {
                return ResourceManager.GetString("IndicoScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API Key used to connect to your API..
        /// </summary>
        internal static string IndicoScopeApiKeyDescription {
            get {
                return ResourceManager.GetString("IndicoScopeApiKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        internal static string IndicoScopeApiKeyDisplayName {
            get {
                return ResourceManager.GetString("IndicoScopeApiKeyDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address for the Indico API URL to connect to..
        /// </summary>
        internal static string IndicoScopeApiURLDescription {
            get {
                return ResourceManager.GetString("IndicoScopeApiURLDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico API URL.
        /// </summary>
        internal static string IndicoScopeApiURLDisplayName {
            get {
                return ResourceManager.GetString("IndicoScopeApiURLDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scope that connects to your Indico API..
        /// </summary>
        internal static string IndicoScopeDescription {
            get {
                return ResourceManager.GetString("IndicoScopeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain to use for this model.
        /// </summary>
        internal static string IndicoScopeModelDomainDescription {
            get {
                return ResourceManager.GetString("IndicoScopeModelDomainDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Domain.
        /// </summary>
        internal static string IndicoScopeModelDomainDisplayName {
            get {
                return ResourceManager.GetString("IndicoScopeModelDomainDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the custom collection to interact with.
        /// </summary>
        internal static string IndicoScopeModelNameDescription {
            get {
                return ResourceManager.GetString("IndicoScopeModelNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Collection Name.
        /// </summary>
        internal static string IndicoScopeModelNameDisplayName {
            get {
                return ResourceManager.GetString("IndicoScopeModelNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of labeled data items.
        /// </summary>
        internal static string LabeledDataArgumentDescription {
            get {
                return ResourceManager.GetString("LabeledDataArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labeled Data.
        /// </summary>
        internal static string LabeledDataArgumentDisplayName {
            get {
                return ResourceManager.GetString("LabeledDataArgumentDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True if the labeled data was added successfully.
        /// </summary>
        internal static string LabeledDataResultsDescription {
            get {
                return ResourceManager.GetString("LabeledDataResultsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string LabeledDataResultsDisplayName {
            get {
                return ResourceManager.GetString("LabeledDataResultsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists all collections associated with your account.
        /// </summary>
        internal static string ListCollectionsDescription {
            get {
                return ResourceManager.GetString("ListCollectionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Collections.
        /// </summary>
        internal static string ListCollectionsDisplayName {
            get {
                return ResourceManager.GetString("ListCollectionsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}.
        /// </summary>
        internal static string MetadataValidationError {
            get {
                return ResourceManager.GetString("MetadataValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Information.
        /// </summary>
        internal static string ModelInformation {
            get {
                return ResourceManager.GetString("ModelInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
    }
}
