//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indico.Custom.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Indico.Custom.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The child activity that goes inside the scope..
        /// </summary>
        internal static string ChildActivityDescription {
            get {
                return ResourceManager.GetString("ChildActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Activity.
        /// </summary>
        internal static string ChildActivityDisplayName {
            get {
                return ResourceManager.GetString("ChildActivityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first value that you want to sum..
        /// </summary>
        internal static string ChildActivityFirstValueDescription {
            get {
                return ResourceManager.GetString("ChildActivityFirstValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstValue.
        /// </summary>
        internal static string ChildActivityFirstValueDisplayName {
            get {
                return ResourceManager.GetString("ChildActivityFirstValueDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second value you want to sum..
        /// </summary>
        internal static string ChildActivitySecondValueDescription {
            get {
                return ResourceManager.GetString("ChildActivitySecondValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecondValue.
        /// </summary>
        internal static string ChildActivitySecondValueDisplayName {
            get {
                return ResourceManager.GetString("ChildActivitySecondValueDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sum of the two values provided..
        /// </summary>
        internal static string ChildActivitySumDescription {
            get {
                return ResourceManager.GetString("ChildActivitySumDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        internal static string ChildActivitySumDisplayName {
            get {
                return ResourceManager.GetString("ChildActivitySumDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico Custom Scope.
        /// </summary>
        internal static string IndicoScope {
            get {
                return ResourceManager.GetString("IndicoScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API Key used to connect to your API..
        /// </summary>
        internal static string IndicoScopeApiKeyDescription {
            get {
                return ResourceManager.GetString("IndicoScopeApiKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        internal static string IndicoScopeApiKeyDisplayName {
            get {
                return ResourceManager.GetString("IndicoScopeApiKeyDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address for the Indico API URL to connect to..
        /// </summary>
        internal static string IndicoScopeApiURLDescription {
            get {
                return ResourceManager.GetString("IndicoScopeApiURLDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico API URL.
        /// </summary>
        internal static string IndicoScopeApiURLDisplayName {
            get {
                return ResourceManager.GetString("IndicoScopeApiURLDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scope that connects to your Indico API..
        /// </summary>
        internal static string IndicoScopeDescription {
            get {
                return ResourceManager.GetString("IndicoScopeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}.
        /// </summary>
        internal static string MetadataValidationError {
            get {
                return ResourceManager.GetString("MetadataValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
    }
}
