//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indico.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Indico.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds labled data to a custom collection.
        /// </summary>
        internal static string AddDataDescription {
            get {
                return ResourceManager.GetString("AddDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Data.
        /// </summary>
        internal static string AddDataDisplayName {
            get {
                return ResourceManager.GetString("AddDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotations for the provided examples.
        /// </summary>
        internal static string AnnotationResultsDescription {
            get {
                return ResourceManager.GetString("AnnotationResultsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation Predictions.
        /// </summary>
        internal static string AnnotationResultsDisplayName {
            get {
                return ResourceManager.GetString("AnnotationResultsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True if the authorization was successful.
        /// </summary>
        internal static string AuthorizeSuccessDescription {
            get {
                return ResourceManager.GetString("AuthorizeSuccessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string AuthorizeSuccessDisplayName {
            get {
                return ResourceManager.GetString("AuthorizeSuccessDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant user permissions on a collection.
        /// </summary>
        internal static string AuthorizeUserDescription {
            get {
                return ResourceManager.GetString("AuthorizeUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize User.
        /// </summary>
        internal static string AuthorizeUserDisplayName {
            get {
                return ResourceManager.GetString("AuthorizeUserDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Email.
        /// </summary>
        internal static string AuthorizeUserEmailDisplayName {
            get {
                return ResourceManager.GetString("AuthorizeUserEmailDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email associated with the user account.
        /// </summary>
        internal static string AuthorizeUserEmailsDescription {
            get {
                return ResourceManager.GetString("AuthorizeUserEmailsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which permission to grant.
        /// </summary>
        internal static string AuthorizeUserPermissionDescription {
            get {
                return ResourceManager.GetString("AuthorizeUserPermissionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        internal static string AuthorizeUserPermissionDisplayName {
            get {
                return ResourceManager.GetString("AuthorizeUserPermissionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Info.
        /// </summary>
        internal static string CollectionInfoCategoryName {
            get {
                return ResourceManager.GetString("CollectionInfoCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns info about the collection.
        /// </summary>
        internal static string CollectionInfoDescription {
            get {
                return ResourceManager.GetString("CollectionInfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Info.
        /// </summary>
        internal static string CollectionInfoDisplayName {
            get {
                return ResourceManager.GetString("CollectionInfoDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object containing information about the given collection.
        /// </summary>
        internal static string CollectionInfoResultsDescription {
            get {
                return ResourceManager.GetString("CollectionInfoResultsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Information.
        /// </summary>
        internal static string CollectionInfoResultsDisplayName {
            get {
                return ResourceManager.GetString("CollectionInfoResultsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of indico Custom Collections.
        /// </summary>
        internal static string CollectionListResultsDescription {
            get {
                return ResourceManager.GetString("CollectionListResultsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string CollectionListResultsDisplayName {
            get {
                return ResourceManager.GetString("CollectionListResultsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True if the de-authorization was successful.
        /// </summary>
        internal static string DeAuthorizeSuccessDescription {
            get {
                return ResourceManager.GetString("DeAuthorizeSuccessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string DeAuthorizeSuccessDisplayName {
            get {
                return ResourceManager.GetString("DeAuthorizeSuccessDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revokes user permissions on a collection.
        /// </summary>
        internal static string DeAuthorizeUserDescription {
            get {
                return ResourceManager.GetString("DeAuthorizeUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De-Authorize User.
        /// </summary>
        internal static string DeAuthorizeUserDisplayName {
            get {
                return ResourceManager.GetString("DeAuthorizeUserDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Email.
        /// </summary>
        internal static string DeAuthorizeUserEmailDisplayName {
            get {
                return ResourceManager.GetString("DeAuthorizeUserEmailDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email associated with the user account.
        /// </summary>
        internal static string DeAuthorizeUserEmailsDescription {
            get {
                return ResourceManager.GetString("DeAuthorizeUserEmailsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configures a collection to not be shareable.
        /// </summary>
        internal static string DeregisterCollectionDescription {
            get {
                return ResourceManager.GetString("DeregisterCollectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpublish Collection.
        /// </summary>
        internal static string DeregisterCollectionDisplayName {
            get {
                return ResourceManager.GetString("DeregisterCollectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deregistration of collection complete.
        /// </summary>
        internal static string DeregisterSuccessDescription {
            get {
                return ResourceManager.GetString("DeregisterSuccessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string DeregisterSuccessDisplayName {
            get {
                return ResourceManager.GetString("DeregisterSuccessDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of text or base 64 encoded image examples.
        /// </summary>
        internal static string ExamplesDataArgumentDescription {
            get {
                return ResourceManager.GetString("ExamplesDataArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        internal static string ExamplesDataArgumentDisplayName {
            get {
                return ResourceManager.GetString("ExamplesDataArgumentDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation of predictions for the provided examples.
        /// </summary>
        internal static string ExplainResultsDescription {
            get {
                return ResourceManager.GetString("ExplainResultsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prediction Explanations.
        /// </summary>
        internal static string ExplainResultsDisplayName {
            get {
                return ResourceManager.GetString("ExplainResultsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns info about the Finetune collection.
        /// </summary>
        internal static string FinetuneCollectionInfoDescription {
            get {
                return ResourceManager.GetString("FinetuneCollectionInfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finetune Collection Info.
        /// </summary>
        internal static string FinetuneCollectionInfoDisplayName {
            get {
                return ResourceManager.GetString("FinetuneCollectionInfoDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the finetune collection to interact with.
        /// </summary>
        internal static string FinetuneModelNameDescription {
            get {
                return ResourceManager.GetString("FinetuneModelNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinetuneCollection Name.
        /// </summary>
        internal static string FinetuneModelNameDisplayName {
            get {
                return ResourceManager.GetString("FinetuneModelNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns annotation predictions for given examples.
        /// </summary>
        internal static string GetAnnotationsDescription {
            get {
                return ResourceManager.GetString("GetAnnotationsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predict (Annotations).
        /// </summary>
        internal static string GetAnnotationsDisplayName {
            get {
                return ResourceManager.GetString("GetAnnotationsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns prediction explanations for given examples.
        /// </summary>
        internal static string GetExplanationsDescription {
            get {
                return ResourceManager.GetString("GetExplanationsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explain (Classification).
        /// </summary>
        internal static string GetExplanationsDisplayName {
            get {
                return ResourceManager.GetString("GetExplanationsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finetune predictions for the provided examples.
        /// </summary>
        internal static string GetFinetunePredictionsDescription {
            get {
                return ResourceManager.GetString("GetFinetunePredictionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finetune Predictions.
        /// </summary>
        internal static string GetFinetunePredictionsDisplayName {
            get {
                return ResourceManager.GetString("GetFinetunePredictionsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns classification predictions for given examples.
        /// </summary>
        internal static string GetPredictionsDescription {
            get {
                return ResourceManager.GetString("GetPredictionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predict (Classification).
        /// </summary>
        internal static string GetPredictionsDisplayName {
            get {
                return ResourceManager.GetString("GetPredictionsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico Application Scope.
        /// </summary>
        internal static string IndicoScope {
            get {
                return ResourceManager.GetString("IndicoScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API Key used to connect to your API..
        /// </summary>
        internal static string IndicoScopeApiKeyDescription {
            get {
                return ResourceManager.GetString("IndicoScopeApiKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        internal static string IndicoScopeApiKeyDisplayName {
            get {
                return ResourceManager.GetString("IndicoScopeApiKeyDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address for the Indico API URL to connect to..
        /// </summary>
        internal static string IndicoScopeApiURLDescription {
            get {
                return ResourceManager.GetString("IndicoScopeApiURLDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico API URL.
        /// </summary>
        internal static string IndicoScopeApiURLDisplayName {
            get {
                return ResourceManager.GetString("IndicoScopeApiURLDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scope that connects to your Indico API..
        /// </summary>
        internal static string IndicoScopeDescription {
            get {
                return ResourceManager.GetString("IndicoScopeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of labeled data items.
        /// </summary>
        internal static string LabeledDataArgumentDescription {
            get {
                return ResourceManager.GetString("LabeledDataArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labeled Data.
        /// </summary>
        internal static string LabeledDataArgumentDisplayName {
            get {
                return ResourceManager.GetString("LabeledDataArgumentDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True if the labeled data was added successfully.
        /// </summary>
        internal static string LabeledDataResultsDescription {
            get {
                return ResourceManager.GetString("LabeledDataResultsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string LabeledDataResultsDisplayName {
            get {
                return ResourceManager.GetString("LabeledDataResultsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists all collections associated with your account.
        /// </summary>
        internal static string ListCollectionsDescription {
            get {
                return ResourceManager.GetString("ListCollectionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Collections.
        /// </summary>
        internal static string ListCollectionsDisplayName {
            get {
                return ResourceManager.GetString("ListCollectionsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads a finetune collection into memory for use.
        /// </summary>
        internal static string LoadFinetuneCollectionDescription {
            get {
                return ResourceManager.GetString("LoadFinetuneCollectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Finetune Collection.
        /// </summary>
        internal static string LoadFinetuneCollectionDisplayName {
            get {
                return ResourceManager.GetString("LoadFinetuneCollectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}.
        /// </summary>
        internal static string MetadataValidationError {
            get {
                return ResourceManager.GetString("MetadataValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain to use for this model.
        /// </summary>
        internal static string ModelDomainDescription {
            get {
                return ResourceManager.GetString("ModelDomainDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Domain.
        /// </summary>
        internal static string ModelDomainDisplayName {
            get {
                return ResourceManager.GetString("ModelDomainDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the custom collection to interact with.
        /// </summary>
        internal static string ModelNameDescription {
            get {
                return ResourceManager.GetString("ModelNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Collection Name.
        /// </summary>
        internal static string ModelNameDisplayName {
            get {
                return ResourceManager.GetString("ModelNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL or File Name.
        /// </summary>
        internal static string PdfDataArgumentDescription {
            get {
                return ResourceManager.GetString("PdfDataArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF File.
        /// </summary>
        internal static string PdfDataArgumentDisplayName {
            get {
                return ResourceManager.GetString("PdfDataArgumentDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracted Pages.
        /// </summary>
        internal static string PdfExtractedPagesDisplayName {
            get {
                return ResourceManager.GetString("PdfExtractedPagesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracts data from a PDF.
        /// </summary>
        internal static string PDFExtractionActivityDescription {
            get {
                return ResourceManager.GetString("PDFExtractionActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Extraction.
        /// </summary>
        internal static string PDFExtractionActivityDisplayName {
            get {
                return ResourceManager.GetString("PDFExtractionActivityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracts the text and tables from PDF documents.
        /// </summary>
        internal static string PdfExtractionDescription {
            get {
                return ResourceManager.GetString("PdfExtractionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract PDF.
        /// </summary>
        internal static string PdfExtractionDisplayName {
            get {
                return ResourceManager.GetString("PdfExtractionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return metadata if available?.
        /// </summary>
        internal static string PdfImagesFlagDescription {
            get {
                return ResourceManager.GetString("PdfImagesFlagDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Images.
        /// </summary>
        internal static string PdfImagesFlagDisplayName {
            get {
                return ResourceManager.GetString("PdfImagesFlagDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return all the images in the PDF file in PIL format?.
        /// </summary>
        internal static string PdfMetadataFlagDescription {
            get {
                return ResourceManager.GetString("PdfMetadataFlagDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Metadata.
        /// </summary>
        internal static string PdfMetadataFlagDisplayName {
            get {
                return ResourceManager.GetString("PdfMetadataFlagDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Metadata.
        /// </summary>
        internal static string PdfMetadatasDisplayName {
            get {
                return ResourceManager.GetString("PdfMetadatasDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proces document with OCR before extraction.
        /// </summary>
        internal static string PdfOCRFlagDescription {
            get {
                return ResourceManager.GetString("PdfOCRFlagDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use OCR?.
        /// </summary>
        internal static string PdfOCRFlagDisplayName {
            get {
                return ResourceManager.GetString("PdfOCRFlagDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treat contents as a single column.
        /// </summary>
        internal static string PdfSingleColumnDescription {
            get {
                return ResourceManager.GetString("PdfSingleColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Column.
        /// </summary>
        internal static string PdfSingleColumnDisplayName {
            get {
                return ResourceManager.GetString("PdfSingleColumnDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return the contents of tables in the document, separately from body text?.
        /// </summary>
        internal static string PdfTablesFlagDescription {
            get {
                return ResourceManager.GetString("PdfTablesFlagDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Tables.
        /// </summary>
        internal static string PdfTablesFlagDisplayName {
            get {
                return ResourceManager.GetString("PdfTablesFlagDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return all body text (separately from headers, footers, and tables)?.
        /// </summary>
        internal static string PdfTextFlagDescription {
            get {
                return ResourceManager.GetString("PdfTextFlagDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Text.
        /// </summary>
        internal static string PdfTextFlagDisplayName {
            get {
                return ResourceManager.GetString("PdfTextFlagDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictions for the provided examples.
        /// </summary>
        internal static string PredictionResultsDescription {
            get {
                return ResourceManager.GetString("PredictionResultsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictions.
        /// </summary>
        internal static string PredictionResultsDisplayName {
            get {
                return ResourceManager.GetString("PredictionResultsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configures a collection to be sharable.
        /// </summary>
        internal static string RegisterCollectionDescription {
            get {
                return ResourceManager.GetString("RegisterCollectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Collection.
        /// </summary>
        internal static string RegisterCollectionDisplayName {
            get {
                return ResourceManager.GetString("RegisterCollectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True if the collection should be publicly available.
        /// </summary>
        internal static string RegisterCollectionMakePublicDescription {
            get {
                return ResourceManager.GetString("RegisterCollectionMakePublicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Public.
        /// </summary>
        internal static string RegisterCollectionMakePublicDisplayName {
            get {
                return ResourceManager.GetString("RegisterCollectionMakePublicDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registeration collection complete.
        /// </summary>
        internal static string RegisterSuccessDescription {
            get {
                return ResourceManager.GetString("RegisterSuccessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string RegisterSuccessDisplayName {
            get {
                return ResourceManager.GetString("RegisterSuccessDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears and deletes a custom collection.
        /// </summary>
        internal static string RemoveCollectionDescription {
            get {
                return ResourceManager.GetString("RemoveCollectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Collection.
        /// </summary>
        internal static string RemoveCollectionDisplayName {
            get {
                return ResourceManager.GetString("RemoveCollectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes example data from a collection.
        /// </summary>
        internal static string RemoveDataDescription {
            get {
                return ResourceManager.GetString("RemoveDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Example Data.
        /// </summary>
        internal static string RemoveDataDisplayName {
            get {
                return ResourceManager.GetString("RemoveDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of examples to remove.
        /// </summary>
        internal static string RemoveExamplesDescription {
            get {
                return ResourceManager.GetString("RemoveExamplesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        internal static string RemoveExamplesDisplayName {
            get {
                return ResourceManager.GetString("RemoveExamplesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True if the removal was successful.
        /// </summary>
        internal static string RemoveSuccessDescription {
            get {
                return ResourceManager.GetString("RemoveSuccessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string RemoveSuccessDisplayName {
            get {
                return ResourceManager.GetString("RemoveSuccessDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiate training on the custom collection.
        /// </summary>
        internal static string TrainCollectionDescription {
            get {
                return ResourceManager.GetString("TrainCollectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Collection.
        /// </summary>
        internal static string TrainCollectionDisplayName {
            get {
                return ResourceManager.GetString("TrainCollectionDisplayName", resourceCulture);
            }
        }
    }
}
