//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indico.Activities.Design.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Indico.Activities.Design.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labeled Data.
        /// </summary>
        public static string AddDataInput {
            get {
                return ResourceManager.GetString("AddDataInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of CollectionData Objects.
        /// </summary>
        public static string AddDataTextHint {
            get {
                return ResourceManager.GetString("AddDataTextHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico.
        /// </summary>
        public static string BaseCategory {
            get {
                return ResourceManager.GetString("BaseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico.Custom.
        /// </summary>
        public static string CustomCategory {
            get {
                return ResourceManager.GetString("CustomCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click to view.
        /// </summary>
        public static string DoubleClickToView {
            get {
                return ResourceManager.GetString("DoubleClickToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Activity Here.
        /// </summary>
        public static string DropActivityHere {
            get {
                return ResourceManager.GetString("DropActivityHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico.Finetune.
        /// </summary>
        public static string FinetuneCategory {
            get {
                return ResourceManager.GetString("FinetuneCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of text or base64 encoded image samples.
        /// </summary>
        public static string GetExplanationsHint {
            get {
                return ResourceManager.GetString("GetExplanationsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        public static string GetExplanationsInput {
            get {
                return ResourceManager.GetString("GetExplanationsInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of text or base64 encoded image samples.
        /// </summary>
        public static string GetPredictionsHint {
            get {
                return ResourceManager.GetString("GetPredictionsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        public static string GetPredictionsInput {
            get {
                return ResourceManager.GetString("GetPredictionsInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Name.
        /// </summary>
        public static string ModelNameInput {
            get {
                return ResourceManager.GetString("ModelNameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the custom collection to use.
        /// </summary>
        public static string ModelNameInputHint {
            get {
                return ResourceManager.GetString("ModelNameInputHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico.PDF Extraction.
        /// </summary>
        public static string PDFExtractionCategory {
            get {
                return ResourceManager.GetString("PDFExtractionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF File.
        /// </summary>
        public static string PDFFilenameInput {
            get {
                return ResourceManager.GetString("PDFFilenameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to a PDF file.
        /// </summary>
        public static string PDFFilenameInputHint {
            get {
                return ResourceManager.GetString("PDFFilenameInputHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of text or base 64 encoded image exampes to be removed.
        /// </summary>
        public static string RemoveExamplesHint {
            get {
                return ResourceManager.GetString("RemoveExamplesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        public static string RemoveExamplesInput {
            get {
                return ResourceManager.GetString("RemoveExamplesInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indico.Custom.Sharing.
        /// </summary>
        public static string SharingCategory {
            get {
                return ResourceManager.GetString("SharingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Email.
        /// </summary>
        public static string UserEmailInput {
            get {
                return ResourceManager.GetString("UserEmailInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email for user&apos;s account.
        /// </summary>
        public static string UserInputHint {
            get {
                return ResourceManager.GetString("UserInputHint", resourceCulture);
            }
        }
    }
}
